// External Code Systems with a canonical recognized by terminology.hl7.org
Alias:   LNC = http://loinc.org
Alias:   SCT = http://snomed.info/sct
//Alias:   SCT = http://snomed.info/sct|http://snomed.info/sct/731000124108   // latest US edition (see exp-params.json)
//Alias:   SCT = http://snomed.info/sct|http://snomed.info/sct/900000000000207008   // Latest international edition
Alias:   UCUM = http://unitsofmeasure.org
Alias:   ICD10CM = http://hl7.org/fhir/sid/icd-10-cm
Alias:   ICD10PCS = http://www.cms.gov/Medicare/Coding/ICD10
Alias:   RXN = http://www.nlm.nih.gov/research/umls/rxnorm
Alias:   v2-0487 = http://terminology.hl7.org/CodeSystem/v2-0487
Alias: CAP = http://cap.org/eCC
Alias: MPC = http://hl7.org/fhir/message-significance-category
Alias: trigdef = http://hl7.org/fhir/us/medmorph/CodeSystem/us-ph-triggerdefinition-namedevents
Alias: uspathtype = http://terminology.hl7.org/CodeSystem/v2-0443
Alias: phmsgheader = http://hl7.org/fhir/us/medmorph/CodeSystem/us-ph-messageheader-message-types
Alias: reportinit = http://hl7.org/fhir/us/medmorph/CodeSystem/us-ph-report-initiation-types
Alias: $v3-ActCode = http://terminology.hl7.org/CodeSystem/v3-ActCode
Alias: $condition-clinical = http://terminology.hl7.org/CodeSystem/condition-clinical
Alias: $condition-ver-status = http://terminology.hl7.org/CodeSystem/condition-ver-status
Alias: $condition-category = http://terminology.hl7.org/CodeSystem/condition-category
Alias: $allergyintolerance-clinical = http://terminology.hl7.org/CodeSystem/allergyintolerance-clinical
Alias: $allergyintolerance-verification = http://terminology.hl7.org/CodeSystem/allergyintolerance-verification
